### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by certainlyjacked** [kirsle/follow-sync#1]
Could you please explain how to use the script on windows?

Thank you

**Comment by kirsle** [comment]
Use the `run-me.bat` file from the Windows release zip file to run the program. It just runs the .exe file and then uses a `pause` command so that the command prompt window won't close immediately when the program exits (in case of an error or if it just finishes its task and exits). Otherwise, open a command prompt manually and navigate to the directory where you extracted the program and run it that way.

To run it from source instead of the binary, install the [Go language](https://golang.org/dl/), get a command prompt window pointing at the source directory, run `go get ./...` to install its dependencies (for the Instagram unofficial API), and `go run main.go` to run the program.

**Comment by certainlyjacked** [comment]
Actually, I can't find the .bat file you're referring to?

**Comment by kirsle** [comment]
It's in the zip files for Windows on the releases page: [here](https://github.com/kirsle/follow-sync/releases). Get the `windows-amd64.zip` if you have a 64-bit computer or `windows-386.zip` for 32-bit.

**Comment by certainlyjacked** [comment]
Thanks mate - didn't see that
